# Generated by Django 4.2.7 on 2025-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('compound_score', models.FloatField()),
                ('positive_score', models.FloatField()),
                ('negative_score', models.FloatField()),
                ('neutral_score', models.FloatField()),
                ('source', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analytics_s_symbol_c5d6b3_idx'), models.Index(fields=['timestamp'], name='analytics_s_timesta_b21a50_idx')],
                'unique_together': {('symbol', 'timestamp', 'source')},
            },
        ),
    ]
