# Generated by Django 5.2.5 on 2025-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sentimentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FearGreedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('volatility_score', models.IntegerField(blank=True, null=True)),
                ('market_momentum_score', models.IntegerField(blank=True, null=True)),
                ('social_media_score', models.IntegerField(blank=True, null=True)),
                ('survey_score', models.IntegerField(blank=True, null=True)),
                ('junk_bond_demand_score', models.IntegerField(blank=True, null=True)),
                ('safe_haven_demand_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_f_date_deeaf6_idx'), models.Index(fields=['value'], name='analytics_f_value_d7ee9e_idx'), models.Index(fields=['classification'], name='analytics_f_classif_6dc059_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSentimentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeframe', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=3)),
                ('fear_greed_index', models.IntegerField(blank=True, null=True)),
                ('fear_greed_label', models.CharField(blank=True, max_length=20)),
                ('vix_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vix_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vix_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('put_call_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('put_call_ratio_change', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('market_mood', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('volatility_regime', models.CharField(blank=True, max_length=20)),
                ('trend_strength', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'timeframe'], name='analytics_m_timesta_9f9871_idx'), models.Index(fields=['fear_greed_index'], name='analytics_m_fear_gr_3454e4_idx'), models.Index(fields=['vix_value'], name='analytics_m_vix_val_ffd155_idx'), models.Index(fields=['put_call_ratio'], name='analytics_m_put_cal_b8925f_idx')],
                'unique_together': {('timestamp', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='PutCallRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('total_put_call_ratio', models.DecimalField(decimal_places=3, max_digits=6)),
                ('equity_put_call_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('index_put_call_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('etf_put_call_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('total_put_volume', models.BigIntegerField(blank=True, null=True)),
                ('total_call_volume', models.BigIntegerField(blank=True, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sma_10', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sma_20', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_p_date_b65d23_idx'), models.Index(fields=['total_put_call_ratio'], name='analytics_p_total_p_9d005b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VIXData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('open_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sma_20', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_v_date_13b225_idx'), models.Index(fields=['close_value'], name='analytics_v_close_v_5ae37b_idx')],
            },
        ),
    ]
