# Generated by Django 5.2.5 on 2025-08-21 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_tradingsignal_sector_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='entry_confidence',
            field=models.FloatField(blank=True, default=0.8, help_text='Confidence in entry point accuracy (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='entry_point_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed entry point analysis (levels, patterns, indicators)'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='entry_point_type',
            field=models.CharField(blank=True, choices=[('SUPPORT_BREAK', 'Support Break'), ('RESISTANCE_BREAK', 'Resistance Break'), ('SUPPORT_BOUNCE', 'Support Bounce'), ('RESISTANCE_REJECTION', 'Resistance Rejection'), ('BREAKOUT', 'Breakout'), ('BREAKDOWN', 'Breakdown'), ('MEAN_REVERSION', 'Mean Reversion'), ('TREND_FOLLOWING', 'Trend Following'), ('CONSOLIDATION_BREAK', 'Consolidation Break'), ('VOLUME_SPIKE', 'Volume Spike'), ('PATTERN_COMPLETION', 'Pattern Completion'), ('INDICATOR_CROSSOVER', 'Indicator Crossover')], default='TREND_FOLLOWING', help_text='Type of entry point identified', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='entry_zone_high',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Upper bound of entry zone', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='entry_zone_low',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Lower bound of entry zone', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('1M', '1 Minute'), ('5M', '5 Minutes'), ('15M', '15 Minutes'), ('30M', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month')], default='1H', help_text='Timeframe used for signal analysis', max_length=10, null=True),
        ),
    ]
