# Generated by Django 5.2.5 on 2025-10-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_fix_created_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketregime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signalalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signalperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spotportfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spottradingsignal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
