# Generated by Django 5.2.5 on 2026-01-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0017_alter_marketregime_created_at_and_more'),
        ('trading', '0006_symbol_circulating_supply_symbol_total_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='best_of_day_date',
            field=models.DateField(blank=True, help_text='Date when this signal was marked as best of day', null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='best_of_day_rank',
            field=models.IntegerField(blank=True, help_text='Rank of this signal among best signals of the day (1 = best)', null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='is_best_of_day',
            field=models.BooleanField(default=False, help_text='Marked as one of the best signals of the day'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['is_best_of_day', 'best_of_day_date'], name='signals_tra_is_best_acd201_idx'),
        ),
    ]
