# Generated by Django 5.2.5 on 2026-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0018_add_daily_best_signals_fields'),
        ('trading', '0006_symbol_circulating_supply_symbol_total_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='signal_date',
            field=models.DateField(blank=True, db_index=True, help_text='Calendar date (UTC) this signal was generated for', null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='signal_hour',
            field=models.IntegerField(blank=True, db_index=True, help_text='Hour of day (0-23 UTC) this signal was generated for', null=True),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['signal_date', 'signal_hour'], name='signals_tra_signal__07ef73_idx'),
        ),
    ]
