# Generated by Django 5.2.5 on 2026-02-05 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_add_signal_date_hour_and_unique_per_day'),
        ('trading', '0006_symbol_circulating_supply_symbol_total_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyBestSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(db_index=True, help_text='Calendar date (UTC) for this hourly slot')),
                ('signal_hour', models.IntegerField(db_index=True, help_text='Hour of day 0-23 UTC', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('rank', models.PositiveSmallIntegerField(help_text='Rank within this hour (1 = best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_score', models.FloatField(blank=True, help_text='Snapshot of signal quality when selected', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
                ('trading_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_best_entries', to='signals.tradingsignal')),
            ],
            options={
                'verbose_name': 'Hourly Best Signal',
                'verbose_name_plural': 'Hourly Best Signals',
                'ordering': ['signal_date', 'signal_hour', 'rank'],
                'indexes': [models.Index(fields=['signal_date', 'signal_hour'], name='signals_hou_signal__3423a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('signal_date', 'signal_hour', 'symbol'), name='unique_symbol_per_hour_per_day')],
            },
        ),
    ]
