# Generated by Django 5.2.5 on 2025-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_symbol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, help_text='Market cap ranking', null=True),
        ),
    ]
