# Generated by Django 5.2.5 on 2025-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_symbol_market_cap_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Circulating supply', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Total supply', max_digits=20, null=True),
        ),
    ]
