# Generated by Django 4.2.7 on 2025-08-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('WEBSOCKET', 'WebSocket'), ('FILE', 'File'), ('DATABASE', 'Database')], max_length=10)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('MARKET_DATA', 'Market Data'), ('TECHNICAL_INDICATORS', 'Technical Indicators'), ('SIGNALS', 'Signals')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_added', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feed_type', models.CharField(choices=[('REALTIME', 'Real-time'), ('HISTORICAL', 'Historical'), ('STREAMING', 'Streaming')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datasource')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD'), ('BB', 'Bollinger Bands'), ('ATR', 'Average True Range'), ('STOCH', 'Stochastic'), ('CCI', 'Commodity Channel Index')], max_length=10)),
                ('period', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'indicator_type', 'timestamp'], name='data_techni_symbol__5a91e8_idx')],
                'unique_together': {('symbol', 'indicator_type', 'period', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_market_symbol__a86f1d_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
