# Generated by Django 5.2.5 on 2025-08-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_marketdata_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalindicator',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.datasource'),
        ),
    ]
