# Generated by Django 5.2.5 on 2025-10-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_sector_sectorcorrelation_sectorperformance_and_more'),
        ('trading', '0006_symbol_circulating_supply_symbol_total_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('total_expected_records', models.IntegerField()),
                ('total_actual_records', models.IntegerField()),
                ('missing_records', models.IntegerField()),
                ('completeness_percentage', models.FloatField()),
                ('has_gaps', models.BooleanField(default=False)),
                ('has_anomalies', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDataRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('earliest_date', models.DateTimeField()),
                ('latest_date', models.DateTimeField()),
                ('total_records', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='data_market_symbol__a86f1d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='timeframe',
            field=models.CharField(default='1h', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('symbol', 'timestamp', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', 'timestamp', 'timeframe'], name='data_market_symbol__748cec_idx'),
        ),
        migrations.AddField(
            model_name='dataquality',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='historicaldatarange',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol'),
        ),
        migrations.AddIndex(
            model_name='dataquality',
            index=models.Index(fields=['symbol', 'timeframe'], name='data_dataqu_symbol__097163_idx'),
        ),
        migrations.AddIndex(
            model_name='dataquality',
            index=models.Index(fields=['date_range_start', 'date_range_end'], name='data_dataqu_date_ra_d4abef_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatarange',
            index=models.Index(fields=['symbol', 'timeframe'], name='data_histor_symbol__c4c478_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatarange',
            index=models.Index(fields=['latest_date'], name='data_histor_latest__033332_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicaldatarange',
            unique_together={('symbol', 'timeframe')},
        ),
    ]
