# Generated by Django 5.2.5 on 2025-08-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_sector_sectorcorrelation_sectorperformance_and_more'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sector'),
        ),
    ]
