# Generated by Django 5.2.5 on 2025-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_sector_sectorcorrelation_sectorperformance_and_more'),
        ('trading', '0002_symbol_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['symbol'], 'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AddField(
            model_name='symbol',
            name='base_currency',
            field=models.CharField(blank=True, help_text='Base currency (e.g., BTC)', max_length=10),
        ),
        migrations.AddField(
            model_name='symbol',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='is_crypto',
            field=models.BooleanField(default=False, help_text='Is this a cryptocurrency'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='is_futures_tradable',
            field=models.BooleanField(default=False, help_text='Can be traded on futures markets'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='is_spot_tradable',
            field=models.BooleanField(default=False, help_text='Can be traded on spot markets'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='min_spot_trade_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='quote_currency',
            field=models.CharField(blank=True, help_text='Quote currency (e.g., USDT)', max_length=10),
        ),
        migrations.AddField(
            model_name='symbol',
            name='spot_exchange',
            field=models.CharField(blank=True, help_text='Primary spot exchange', max_length=50),
        ),
        migrations.AddField(
            model_name='symbol',
            name='spot_pair_format',
            field=models.CharField(blank=True, help_text='Spot trading pair format (e.g., BTC/USDT)', max_length=20),
        ),
        migrations.AddField(
            model_name='symbol',
            name='spot_trading_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['symbol_type', 'is_active'], name='trading_sym_symbol__765731_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['is_spot_tradable', 'is_futures_tradable'], name='trading_sym_is_spot_0db703_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['market_cap_rank'], name='trading_sym_market__ee17ee_idx'),
        ),
    ]
