# Generated by Django 5.2.5 on 2025-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_symbol_options_symbol_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='symbol',
            name='trading_sym_symbol__765731_idx',
        ),
        migrations.RemoveIndex(
            model_name='symbol',
            name='trading_sym_is_spot_0db703_idx',
        ),
        migrations.RemoveIndex(
            model_name='symbol',
            name='trading_sym_market__ee17ee_idx',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='is_crypto',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='is_futures_tradable',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='market_cap_rank',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='max_supply',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='min_spot_trade_amount',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='quote_currency',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='spot_exchange',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='spot_pair_format',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='spot_trading_fee',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='total_supply',
        ),
        migrations.AddField(
            model_name='symbol',
            name='is_crypto_symbol',
            field=models.BooleanField(default=False, help_text='Is this a cryptocurrency symbol?'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='is_spot_tradable',
            field=models.BooleanField(default=False, help_text='Can this symbol be traded spot?'),
        ),
    ]
