# Generated by Django 5.2.5 on 2025-08-21 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_economicindicator_economicevent_macrosentiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('FINANCIALS', 'Financials'), ('ENERGY', 'Energy'), ('CONSUMER_DISCRETIONARY', 'Consumer Discretionary'), ('CONSUMER_STAPLES', 'Consumer Staples'), ('INDUSTRIALS', 'Industrials'), ('MATERIALS', 'Materials'), ('UTILITIES', 'Utilities'), ('REAL_ESTATE', 'Real Estate'), ('COMMUNICATION', 'Communication Services'), ('CRYPTO_DEFI', 'DeFi'), ('CRYPTO_LAYER1', 'Layer 1'), ('CRYPTO_LAYER2', 'Layer 2'), ('CRYPTO_GAMING', 'Gaming'), ('CRYPTO_MEME', 'Meme Coins'), ('CRYPTO_STABLECOIN', 'Stablecoins')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('market_cap_weight', models.FloatField(default=0.0, help_text='Sector weight in overall market (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year')], max_length=2)),
                ('correlation_coefficient', models.FloatField(help_text='Pearson correlation coefficient (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('p_value', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sample_size', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_a', to='data.sector')),
                ('sector_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_b', to='data.sector')),
            ],
            options={
                'indexes': [models.Index(fields=['sector_a', 'sector_b', 'timeframe'], name='data_sector_sector__875c5d_idx'), models.Index(fields=['correlation_coefficient', 'calculated_at'], name='data_sector_correla_758b66_idx')],
                'unique_together': {('sector_a', 'sector_b', 'timeframe', 'calculated_at')},
            },
        ),
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('daily_return', models.FloatField(default=0.0)),
                ('weekly_return', models.FloatField(default=0.0)),
                ('monthly_return', models.FloatField(default=0.0)),
                ('ytd_return', models.FloatField(default=0.0)),
                ('volatility', models.FloatField(default=0.0, help_text='Annualized volatility', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('momentum_score', models.FloatField(default=0.0, help_text='Momentum score (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relative_strength', models.FloatField(default=0.0, help_text='Relative strength vs market (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('volume_trend', models.FloatField(default=0.0, help_text='Volume trend indicator (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sector')),
            ],
            options={
                'indexes': [models.Index(fields=['sector', 'timestamp'], name='data_sector_sector__c20c8a_idx'), models.Index(fields=['timestamp', 'relative_strength'], name='data_sector_timesta_80bda1_idx')],
                'unique_together': {('sector', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SectorRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_type', models.CharField(choices=[('GROWTH_TO_VALUE', 'Growth to Value'), ('VALUE_TO_GROWTH', 'Value to Growth'), ('DEFENSIVE_TO_CYCLICAL', 'Defensive to Cyclical'), ('CYCLICAL_TO_DEFENSIVE', 'Cyclical to Defensive'), ('RISK_ON', 'Risk On'), ('RISK_OFF', 'Risk Off')], max_length=25)),
                ('strength', models.FloatField(help_text='Rotation strength (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(help_text='Confidence in rotation signal (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('duration_days', models.IntegerField(default=0)),
                ('market_regime', models.CharField(blank=True, max_length=20)),
                ('economic_driver', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations_out', to='data.sector')),
                ('to_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations_in', to='data.sector')),
            ],
            options={
                'indexes': [models.Index(fields=['rotation_type', 'detected_at'], name='data_sector_rotatio_aca343_idx'), models.Index(fields=['from_sector', 'to_sector', 'detected_at'], name='data_sector_from_se_ce60ac_idx')],
            },
        ),
    ]
