"""
Django settings for ai_trading_engine project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
from pathlib import Path
from decouple import config

# PyMySQL configuration (if using PyMySQL instead of mysqlclient)
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# With the new repo layout, `frontend` sits alongside `backend`.
# PROJECT_ROOT refers to the directory that contains both `backend` and `frontend`.
PROJECT_ROOT = BASE_DIR.parent
FRONTEND_DIR = PROJECT_ROOT / 'frontend'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-v%kz(i_y%6y1v7^l9i2i9kxx$s1ia&u5f#_7ww&m7mj)4yi7bd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)  # Temporarily enabled for debugging

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,127.0.0.1:8000').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'channels',  # Added for real-time features
    'storages',  # AWS S3 storage
    
    # Local apps
    'apps.core',
    'apps.trading',
    'apps.signals',
    'apps.data',
    'apps.dashboard',
    'apps.sentiment',
    'apps.analytics',
    'apps.subscription',
]

# Channels Configuration for Real-Time Features
# Using in-memory channel layer for immediate real-time functionality
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Redis Configuration for Channels and Caching
REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0

# Cache Configuration - Using in-memory cache for immediate functionality
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',  # Not required for allauth 0.54.0
    'apps.core.middleware.PerformanceMonitoringMiddleware',
    # 'apps.core.middleware.APIRateLimitMiddleware',  # Disabled - rate limiting removed
    # 'apps.subscription.middleware.SubscriptionMiddleware',
    # 'apps.subscription.middleware.SubscriptionRedirectMiddleware',
]

ROOT_URLCONF = 'ai_trading_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', FRONTEND_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.live_crypto_prices',
                'apps.core.context_processors.market_status',
                'apps.core.context_processors.admin_dashboard_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_trading_engine.wsgi.application'

# ASGI Application for WebSocket support
ASGI_APPLICATION = 'ai_trading_engine.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database Configuration - MySQL
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='ai_trading_engine'),
        'USER': config('DB_USER', default='trading_user'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'isolation_level': 'read committed',
        },
        'CONN_MAX_AGE': 600,  # 10 minutes connection pooling
        'ATOMIC_REQUESTS': True,
        'AUTOCOMMIT': True,
    }
}

# Database optimization settings for Phase 5
DB_OPTIMIZATION = {
    'QUERY_TIMEOUT': 30,  # seconds
    'MAX_CONNECTIONS': 20,
    'CONNECTION_RETRY_ATTEMPTS': 3,
    'CONNECTION_RETRY_DELAY': 1,  # seconds
    'QUERY_CACHE_TTL': 300,  # 5 minutes
    'SLOW_QUERY_THRESHOLD': 1.0,  # seconds
}

# Database health check settings
DB_HEALTH_CHECK = {
    'ENABLED': True,
    'CHECK_INTERVAL': 300,  # 5 minutes
    'MAX_FAILURES': 3,
    'RECOVERY_TIMEOUT': 60,  # 1 minute
}

# Performance optimization settings for Phase 5
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'cache_table',
#         'TIMEOUT': 300,  # 5 minutes
#         'OPTIONS': {
#             'MAX_ENTRIES': 1000,
#         }
#     }
# }

# Security settings for Phase 5
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session security
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CSRF protection
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_AGE = 31449600  # 1 year

# Rate limiting for API protection
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# AWS S3 Configuration (optional for development)
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    # AWS S3 settings
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    
    # Static files configuration for S3
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    
    # Media files configuration for S3
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    # Remove local static/media settings
    STATIC_ROOT = None
    MEDIA_ROOT = None
else:
    # Local static files configuration
    STATIC_URL = '/static/'
    # Point to the relocated frontend asset directories
    STATIC_ROOT = FRONTEND_DIR / 'staticfiles'
    STATICFILES_DIRS = [
        FRONTEND_DIR / 'static',
        BASE_DIR / 'static',  # Add backend static directory for admin CSS
    ]
    
    # Local media files configuration
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000').split(',')

# Celery settings
# Use Redis by default; override via REDIS_URL env var if needed
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_TASK_ALWAYS_EAGER = False
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Normalize legacy values
if CELERY_RESULT_BACKEND == 'memory':
    CELERY_RESULT_BACKEND = 'cache+memory://'
if CELERY_BROKER_URL == 'memory':
    CELERY_BROKER_URL = 'memory://'

# Trading engine settings
TRADING_SETTINGS = {
    'DEFAULT_CURRENCY': config('DEFAULT_CURRENCY', default='USD'),
    'RISK_PERCENTAGE': config('RISK_PERCENTAGE', default=2.0, cast=float),
    'MAX_POSITION_SIZE': config('MAX_POSITION_SIZE', default=10.0, cast=float),
    'SIGNAL_CONFIDENCE_THRESHOLD': config('SIGNAL_CONFIDENCE_THRESHOLD', default=0.7, cast=float),
    'MODEL_UPDATE_FREQUENCY': config('MODEL_UPDATE_FREQUENCY', default=3600, cast=int),
}

# API Keys for external services
NEWS_API_KEY = config('NEWS_API_KEY', default=None)
CRYPTOPANIC_API_KEY = config('CRYPTOPANIC_API_KEY', default=None)
CRYPTONEWS_API_KEY = config('CRYPTONEWS_API_KEY', default=None)  # CryptoNewsAPI.com
STOCKDATA_API_KEY = config('STOCKDATA_API_KEY', default=None)  # StockData.org

# Enhanced Logging configuration for Phase 5
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}',
            'style': '%',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'trading_engine.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'json_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'trading_engine_json.log',
            'formatter': 'json',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
        },
        'automation_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'automation.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file', 'json_file', 'error_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trading': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.subscription': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.subscription.services': {
            'handlers': ['console', 'file', 'json_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Automation task loggers
        'apps.data.tasks': {
            'handlers': ['console', 'automation_file', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.signals.tasks': {
            'handlers': ['console', 'automation_file', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.signals.unified_signal_task': {
            'handlers': ['console', 'automation_file', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.sentiment.tasks': {
            'handlers': ['console', 'automation_file', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Site configuration for django-allauth
SITE_ID = 1

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@ai-trading-engine.com')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Email Verification Settings
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = 24
EMAIL_VERIFICATION_RESEND_COOLDOWN_MINUTES = 5
EMAIL_VERIFICATION_MAX_ATTEMPTS = 3

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Social Auth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'openid',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': config('GOOGLE_OAUTH2_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH2_CLIENT_SECRET', default=''),
            'key': ''
        },
        'OAUTH_PKCE_ENABLED': True,  # Enhanced security with PKCE
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'picture',
        ],
    }
}

# AllAuth Settings - Updated for Django 5.x compatibility
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
    'signup': '10/h',         # 10 signups per hour
    'password_change': '3/h', # 3 password changes per hour
    'password_reset': '5/h',  # 5 password resets per hour
}
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Google emails are pre-verified
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False  # Don't store OAuth tokens (security best practice)

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Custom error pages
HANDLER404 = 'apps.core.views.handler404'
HANDLER403 = 'apps.core.views.handler403'
HANDLER500 = 'apps.core.views.handler500'

# Celery Beat Schedule - MOVED TO celery.py
# The beat schedule is now configured in ai_trading_engine/celery.py
# This ensures a single source of truth for all Celery configuration
# 
# If you need to add tasks, update celery.py beat_schedule instead of here
# CELERY_BEAT_SCHEDULE = {}  # Disabled - using celery.py instead
