# Generated by Django 4.2.7 on 2025-08-09 09:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0002_marketregime_signalalert_signalfactor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('sma_20', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bollinger_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bollinger_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'date'], name='analytics_m_symbol_01ff98_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('annualized_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticsportfolio')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.tradingsignal')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticsportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PRICE', 'Price Alert'), ('SIGNAL', 'Signal Alert'), ('PORTFOLIO', 'Portfolio Alert'), ('SYSTEM', 'System Alert')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('price_target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRIGGERED', 'Triggered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('cumulative_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('var_95', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticsportfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
