# Generated by Django 4.2.7 on 2025-08-08 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('LSTM', 'LSTM'), ('GRU', 'GRU'), ('TRANSFORMER', 'Transformer'), ('ENSEMBLE', 'Ensemble'), ('CUSTOM', 'Custom')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=4)),
                ('confidence_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('price_target', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('reasoning', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signaltype'),
        ),
        migrations.AddField(
            model_name='signal',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol'),
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_signals', models.IntegerField(default=0)),
                ('correct_signals', models.IntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.aimodel')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol')),
            ],
        ),
    ]
