# Generated by Django 5.2.5 on 2025-08-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_marketregime_signalalert_signalfactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='economic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='signalfactor',
            name='factor_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical Indicator'), ('SENTIMENT', 'Sentiment Analysis'), ('NEWS', 'News Event'), ('VOLUME', 'Volume Analysis'), ('PATTERN', 'Chart Pattern'), ('CORRELATION', 'Correlation Analysis'), ('ECONOMIC', 'Economic/Fundamental Analysis')], max_length=20),
        ),
    ]
