# Generated by Django 5.2.5 on 2025-10-01 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_spotportfolio_tradingtype_spottradingsignal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottradingsignal',
            name='analyzed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when signal was analyzed (Sri Lankan time)'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='analyzed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when signal was analyzed (Sri Lankan time)'),
        ),
    ]
