# Generated by Django 5.2.5 on 2025-10-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_add_analyzed_at_field'),
        ('trading', '0003_alter_symbol_options_symbol_base_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date for backtesting')),
                ('end_date', models.DateField(help_text='End date for backtesting')),
                ('signals_generated', models.IntegerField(default=0, help_text='Number of signals generated')),
                ('search_name', models.CharField(blank=True, help_text='Custom name for this search', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='User notes about this search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_searches', to='trading.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backtest Search',
                'verbose_name_plural': 'Backtest Searches',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'symbol', 'start_date', 'end_date')},
            },
        ),
    ]
