# Generated by Django 5.2.5 on 2025-10-08 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_remove_abtest_model_a_remove_abtest_model_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='analyzed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when signal was analyzed'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='is_hybrid',
            field=models.BooleanField(default=False, help_text='Is this a hybrid signal (spot + futures)?'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
    ]
