# Generated by Django 5.2.5 on 2025-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_tradingsignal_analyzed_at_tradingsignal_is_hybrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketregime',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='signalalert',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='signalperformance',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spotportfolio',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spotposition',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spotsignalhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spottradingsignal',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tradingtype',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
