# Generated by Django 5.2.5 on 2025-12-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription History', 'verbose_name_plural': 'Subscription Histories'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
